[package]
name = "mirage"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
clap_derive = { version = "4.5" }
image = "0.24.3"
num-complex = "0.4.2"
